### PR TITLE
Optional warnings

### LINKED ISSUE #2: Option to disable warnings
https://github.com/tikotzky/inline-environment-variables-webpack-plugin/blob/master/index.js#L46

Something like: 

```
new InlineEnviromentVariablesPlugin({
    NODE_ENV: 'production',
    API_URL: Config.url
}, false)
```

or this:

```
let opts = { warnings: false }
new InlineEnviromentVariablesPlugin({
    NODE_ENV: 'production',
    API_URL: Config.url
}, opts)
```

### PR DESCRIPTION
**Pull request by franvarney**
closes #2 

I can update the README if you like this way of doing it. :)

### CODE REVIEW

**Comment by franvarney** [comment]
Do you think it would be an improvement to add a conditional or assert statement that checks if `userOptions` is actually an object (instead of string or array)?

**Comment by tikotzky** [comment]
thanks for this 😄 
If you can update the readme that would be great.
As for the assert I don't think it's needed, if someone passes in an invalid option they'll figure out pretty quick when it's still `console.warn`ing

**Comment by franvarney** [comment]
Updated 📣

**Comment by tikotzky** [comment]
Awesome!
_and thanks for fixing the typos_ 🙈

**Comment by tikotzky** [comment]
published to npm as v1.1.0 🎉 
Thanks!

**Comment by franvarney** [comment]
You're welcome 🎈

**Pull request merged**
